{% set name = "trame-jupyter-extension" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame_jupyter_extension-{{ version }}.tar.gz
  sha256: f75965a022ace961ce62065f405da48d6558a8391813f8ea4b28d9df4d70215f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python >=3.8
    - jupyterlab >=4,<5
    - jupyter_server >=2.0.1,<3
    - trame >=3.2.7

test:
  imports:
    - trame_jupyter_extension
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kitware/trame-jupyter-extension
  summary: A JupyterLab extension for trame communication layer
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alesgenova
    - jourdain
